wx:
  appId: wxa6d068d78e96683c
  appSecret: c194cedf7a0af4a7296ebe31028c3baa

spring:
  datasource:
    username: corn
    password: Corn#9527
    url: jdbc:mysql://47.112.246.25:3936/sc_user_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      # 抽样率,默认是0.1(10%,表示90%的数据都会丢弃)
      #1.0表示100%,表示所有数据都会上报给zipkin
      probability: 1.0
  cloud:
    nacos:
      server-addr: 47.112.246.25:9488
      discovery:
        namespace: 73be76f5-5fe5-4028-9fc5-d03c169a3cf8
        cluster-name: b-center
        metadata:
          version: v1
    ##sentinel配置
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    ##cloud stream的配置
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: stream-test-topic
          group: binding-group
server:
  port: 8081

rocketmq:
  name-server: 127.0.0.1:9876
##actuator声明
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


# seata相关配置
seata:
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      service_tx_group: default
      enable-degrade: false
      disable-global-transaction: false
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: service_tx_group
  client:
    tm:
      commit-retry-count: 3
      rollback-retry-count: 3
      enable-auto-data-source-proxy: false
    rm:
      report-success-enable: true
      table-meta-check-enable: true
      report-retry-count: 5
      async-commit-buffer-limit: 1000
  transport: # Netty相关配置start
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    enable-client-batch-send-request: true #客户端事务消息请求是否批量合并发送(默认true)
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread