

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/sc_user_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1
  application:
    name: user-service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: 73be76f5-5fe5-4028-9fc5-d03c169a3cf8
        cluster-name: b-center
        metadata:
          version: v1
    ##cloud stream的配置
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
      bindings:
        input:
          destination: stream-test-topic
          group: binding-group
server:
  port: 8081

rocketmq:
  name-server: 127.0.0.1:9876