server:
  port: 8111

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/sc_auth_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1
  application:
    name: auth-center
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: 73be76f5-5fe5-4028-9fc5-d03c169a3cf8

feign:
  client:
    config:
      #全局配置
      default:
        loggerLevel: BASIC
        ##feign拦截器
        requestInterceptors:
          - com.corn.springcloud.authcenter.feign.TokenRelayRequestInterceptor
      ##针对特定的client设置日志级别
      user-service:
        loggerLevel: FULL
  httpclient:
    enabled: true
    # feign 最大连接数
    max-connections: 200
    # feign 单个路径(mapping)的最大连接数
    max-connections-per-route: 1
#默认值可不设置
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml