server:
  port: 8021

spring:
  datasource:
    username: corn
    password: Corn#9527
    url: jdbc:mysql://47.112.246.25:3936/sc_resource_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 12
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 20000
      # 测试sql
      connection-test-query: select 1
  application:
    name: resource-service
  cloud:
    nacos:
      server-addr: 47.112.246.25:9488
      discovery:
        namespace: 73be76f5-5fe5-4028-9fc5-d03c169a3cf8


#默认值可不设置
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml